name: fresh_dio_next
description: An http interceptor for token refresh. Fresh is built on top of package:dio and manages authentication tokens transparently.
repository: https://github.com/TrGiLong/fresh_dio_next
issue_tracker: https://github.com/TrGiLong/fresh_dio_next/issues
homepage: https://github.com/TrGiLong/fresh_dio_next

version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.1
  fresh: ^0.4.0
  fresh_dio: ^0.3.1

dev_dependencies:
  test: ^1.16.0
  test_coverage: ^0.5.0