name: fresh_dio_next
description: An http interceptor for token refresh. Fresh is built on top of package:dio and manages authentication tokens transparently.
repository: https://github.com/TrGiLong/fresh_dio_next
issue_tracker: https://github.com/TrGiLong/fresh_dio_next/issues
homepage: https://github.com/TrGiLong/fresh_dio_next

version: 1.0.0

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  dio: ^4.0.1
  fresh_dio: ^0.3.1

dev_dependencies:
  mocktail: ^0.0.2-dev.5
  test: ^1.16.0
  test_coverage: ^0.5.0